name: Onebeat Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push rcproxy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::682398359195:role/github_actions
          aws-region: us-east-1
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Calver Release
        uses: StephaneBour/actions-calver@v1.5
        id: calver
        with:
          name:
          date_format: "%Y.%m.%d-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/clia/rcproxy:${{ steps.calver.outputs.release }},${{ steps.login-ecr.outputs.registry }}/clia/rcproxy:latest
          cache-from: type=s3,region=us-east-1,bucket=onebeat-github-action-docker-cache,prefix=clia-rcproxy-
          cache-to: type=s3,region=us-east-1,bucket=onebeat-github-action-docker-cache,prefix=clia-rcproxy-

      - name: Release version in the build summary
        run: |
          echo "Release version: ${{ steps.calver.outputs.release }}" >> $GITHUB_STEP_SUMMARY